services:
  - type: web
    name: alfawz-academy
    runtime: node
    plan: free

    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_VERSION
        value: 20

      - key: DATABASE_URL
        sync: false

      - key: AUTH_SECRET
        sync: false

      - key: NEXTAUTH_URL
        sync: false

      - key: RESEND_API_KEY
        sync: false

      - key: PAYSTACK_SECRET_KEY
        sync: false

      - key: NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
        sync: false

      - key: EMAIL_API_KEY
        sync: false

      - key: EMAIL_FROM
        sync: false

      - key: NEXT_PUBLIC_APP_URL
        sync: false

      - key: NEXT_PUBLIC_WHATSAPP_NUMBER
        sync: false